# Generated by Django 4.2.3 on 2023-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prog_Group_no', models.IntegerField()),
                ('Prog_Roll_no', models.IntegerField()),
                ('Prog_Enroll_no', models.IntegerField()),
                ('Prog_Name', models.CharField(max_length=100)),
                ('Prog_Div', models.TextField()),
                ('Prog_Details', models.TextField()),
            ],
            options={
                'db_table': 'Programmers_Details',
            },
        ),
    ]
