# Generated by Django 4.2.3 on 2023-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_programmers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmers',
            name='Prog_Group_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programmers',
            name='Prog_Roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
